#let fc = smallcaps[FlatCombining]
#let fc-banning = smallcaps[FC-Banning]
#let cc-synch = smallcaps[CCSynch]
#let cc-synch-banning = smallcaps[CCSynch-Banning]
#let dsm-synch = smallcaps[DSMSynch]
#let scls = smallcaps[SCLs]
#let u-scl = smallcaps[u-SCL]
#let k-scl = smallcaps[k-SCL]
#let rw-scl = smallcaps[RW-SCL]
#let cfl = smallcaps[CFL]
#let rcl = smallcaps[RCL]
#let ffwd = smallcaps[ffwd]

#let fc-sl = smallcaps[FC-Skiplist]
